#!/usr/bin/env sh

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

texcompile(){ \
	command="pdflatex"
	( sed 5q "$file" | grep -iq 'xelatex' ) && command="xelatex"
	$command --output-directory="$dir" "$base" &&
	grep -i addbibresource "$file" >/dev/null &&
	biber --input-directory "$dir" "$base" $$ &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
}

case "$file" in
	*\.tex) texcompile "$file" ;;
	*\.md) pandoc "$file" --pdf-engine=xelatex -o "$base".pdf ;;
esac


